Repository punker76/MahApps.Metro.SimpleChildWindow, pull requests merged in 2022-10, with the labels that each got.

#126 Update cake build for appveyor
  .config/dotnet-tools.json
  .github/workflows/build.yml
  appveyor.yml
  build.cake
  build.ps1
  cake.config
  src/global.json
Labels: Housekeeping

#127 Add corner radius property to child window
  src/Directory.build.props
  src/Directory.build.targets
  src/MahApps.Metro.SimpleChildWindow.Demo/MahApps.Metro.SimpleChildWindow.Demo.csproj
  src/MahApps.Metro.SimpleChildWindow.Demo/MainWindow.xaml
  src/MahApps.Metro.SimpleChildWindow.sln
  src/MahApps.Metro.SimpleChildWindow/ChildWindow.cs
  src/MahApps.Metro.SimpleChildWindow/MahApps.Metro.SimpleChildWindow.csproj
  src/MahApps.Metro.SimpleChildWindow/Themes/ChildWindow.xaml
Labels: Feature

#128 Check if a dialog is already open and a children of a panel
  src/MahApps.Metro.SimpleChildWindow.Demo/MainWindow.xaml
  src/MahApps.Metro.SimpleChildWindow.Demo/MainWindow.xaml.cs
  src/MahApps.Metro.SimpleChildWindow.Demo/TestChildWindow.xaml.cs
  src/MahApps.Metro.SimpleChildWindow/ChildWindowManager.cs
Labels: Bug

#129 Open child window on controls and not only window
  src/MahApps.Metro.SimpleChildWindow/ChildWindowManager.cs
Labels: Feature

#130 Added properties for min and max width and height
  src/MahApps.Metro.SimpleChildWindow/ChildWindow.cs
  src/MahApps.Metro.SimpleChildWindow/Themes/ChildWindow.xaml
Labels: Feature
